import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import SessionWrapper from "./Components/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Furniture store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      
      </head>
      <body className={inter.className}>
        <SessionWrapper>
          <Navbar />
          {children}
        </SessionWrapper>

      </body>
    </html>
  );
}
